image: node:latest

cache:
  paths:
    - node_modules/
    - build/

stages:
  - test
  - build
  - deploy

before_script:
  - npm -g config set user root
  - npm install -g firebase-tools
  - npm install

test:
  stage: test
  script:
    - echo "Running tests"
    - npm run test

build:
  stage: build
  dependencies:
    - test
  artifacts:
    paths:
    - build/
  script:
    - echo "Building the app"
    - npm run build

deploy:
  stage: deploy
  environment: Production
  dependencies:
    - build
  only:
    - master
  script:
    - firebase deploy --token "*********************************"
